from enum import Enum

# Constant of the number of features generated by the rnn and fc
RNN_FEATURES = 64
FC_FEATURES = 16
STATIC_INPUT_SIZE = 5
DYNAMIC_INPUT_SIZE = 4
TOTAL_FEATURES = FC_FEATURES + RNN_FEATURES


class RNNType(Enum):
    GRU = 0
    LSTM = 1
