permissions:
  contents: read
name: Run Tests 3.12
on:
  workflow_dispatch: # Allow manual triggers
  schedule:
    - cron: 0 0 * * *
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    uses: ./.github/workflows/run_test_base.yml
    with:
      python-version: "3.12"